//         Project / File: DelegationPlugins.Entities / CrmSchemaContracts.cs
// File generated by: CRM Code Generator - Ahmed Elsawalhy (Yagasoft.com)

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;

namespace DelegationPlugins.Entities
{

	#region Contracts

	#endregion

}

